[interne]
; Quand on compose 1001, faire sonner le poste 1001 pendant 20s
exten => 1001,1,Dial(PJSIP/1001,20)
exten => 1001,n,Hangup()

; Quand on compose 1002, faire sonner le poste 1002 pendant 20s
exten => 1002,1,Dial(PJSIP/1002,20)
exten => 1002,n,Hangup()
