apiVersion: v1
kind: Service
metadata:
  name: postgres-replica
  namespace: voip
spec:
  clusterIP: None
  selector:
    app: postgres-replica
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-replica
  namespace: voip
spec:
  serviceName: postgres-replica
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica
  template:
    metadata:
      labels:
        app: postgres-replica
    spec:
      containers:
        - name: postgres-replica
          image: azizdocker2026/postgres-voip:v1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_ROLE
              value: "replica"
            - name: PRIMARY_HOST
              value: "postgres-primary-0.postgres-primary.voip.svc.cluster.local"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres-password
            - name: POSTGRES_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: replication-password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi
