apiVersion: v1
kind: Service
metadata:
  name: asterisk-external
  namespace: {{ .Values.namespace }}
  labels:
    app: asterisk
spec:
  type: NodePort
  selector:
    app: asterisk
  ports:
    - name: sip-udp
      port: 5060
      targetPort: 5060
      nodePort: 31060
      protocol: UDP
