apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-postgres-replication
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - postgres-primary
          - postgres-replica
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - postgres-primary
                  - postgres-replica
      ports:
        - protocol: TCP
          port: 5432
  egress:
    - to:
        - podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - postgres-primary
                  - postgres-replica
      ports:
        - protocol: TCP
          port: 5432
