apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.credentials.postgresPassword | quote }}
  replication-password: {{ .Values.postgres.credentials.replicationPassword | quote }}
